roles:
- name: frontend                    
  jobs:  
  - name: global-properties
    release_name: stratos-ui                         
  - name: frontend
    release_name: stratos-ui            
  run:                      
    scaling:  
      min: 1
      max: 1
    memory: 1024
    virtual-cpus: 2
    exposed-ports:
    - name: frontend-nginx
      protocol: TCP                
      external: 4443              
      internal: 443              
      public: true           

- name: backend                    
  jobs:  
  - name: global-properties
    release_name: stratos-ui                              
  - name: backend
    release_name: stratos-ui            
  run:                      
    scaling:  
      min: 1
      max: 1
    memory: 1024
    virtual-cpus: 2
    exposed-ports:
    - name: backend
      protocol: TCP                
      external: 443              
      internal: 443              
      public: false           

configuration:
  templates:
    properties.stratos_ui.frontend.ssl_cert_key: '"((STRATOS_UI_FRONTEND_SSL_CERT_KEY))"'
    properties.stratos_ui.frontend.ssl_cert: '"((STRATOS_UI_FRONTEND_SSL_CERT))"'
    properties.stratos_ui.backend.host: 'backend.((KUBE_SERVICE_DOMAIN_SUFFIX))'
    properties.stratos_ui.backend.address: '"((IP_ADDRESS))"'
    properties.stratos_ui.backend.ssl_cert_key: '"((STRATOS_UI_BACKEND_SSL_CERT_KEY))"'
    properties.stratos_ui.backend.ssl_cert: '"((STRATOS_UI_BACKEND_SSL_CERT))"'
    properties.stratos_ui.backend.session_store_secret: '"((STRATOS_UI_BACKEND_SESSION_STORE_SECRET))"'
    properties.fissile.monit.user: '"((FISSILE_MONIT_USER))"'
    properties.fissile.monit.password: '"((FISSILE_MONIT_PASSWORD))"'
    properties.fissile.monit.port: '"((FISSILE_MONIT_PORT))"'
  variables:
  - name: FISSILE_MONIT_PASSWORD
    description: Monit port for fissile
    required: true
  - name: FISSILE_MONIT_PORT
    description: Monit port for fissile
    required: true
  - name: FISSILE_MONIT_USER
    description: Fissile Monit user name
    required: true
  - name: KUBE_SERVICE_DOMAIN_SUFFIX
    description: >
      The Kubernetes-internal domain suffix (svc.<namespace>.cluster.local or
      equivalent) to use.  If not specified, it will be auto-detected from the
      runtime configuration.
    immutable: true
    required: false
  - name: STRATOS_UI_BACKEND_SESSION_STORE_SECRET
    description: Session store secret
    secret: true
    required: true
  - name: STRATOS_UI_BACKEND_SSL_CERT
    description: SSL Cert key for Stratos UI backend
    secret: true
    required: true
  - name: STRATOS_UI_BACKEND_SSL_CERT_KEY
    description: SSL Cert for Stratos UI backend
    secret: true
    required: true
  - name: STRATOS_UI_FRONTEND_SSL_CERT
    description: SSL Cert key for Stratos UI frontend
    secret: true
    required: true
  - name: STRATOS_UI_FRONTEND_SSL_CERT_KEY
    description: SSL Cert for Stratos UI frontend
    secret: true
    required: true