# Nightly image build
---
resource_types:
- name: docker-image
  type: docker-image
  privileged: true
  source:
    repository: ((docker-resource-image))

resources:
- name: stratos
  type: git
  source:
    uri: git@github.com:((stratos-repository-organization))/((stratos-repository))
    branch: ((stratos-repository-branch))
    private_key: ((github-private-key))
- name: aio-docker-image
  type: docker-image
  source:
    username: ((docker-username))
    password: ((docker-password))
    repository: ((docker-organization))/((aio-docker-image-name))
- name: after-midnight
  type: time
  source:
    start: 12:00 AM
    stop: 2:00 AM
    location: UTC
    # Docker Images
- name: jetstream-helm-image
  type: docker-image
  source:
    username: ((docker-username))
    password: ((docker-password))
    repository: ((docker-organization))/stratos-jetstream
- name: postflight-helm-image
  type: docker-image
  source:
    username: ((docker-username))
    password: ((docker-password))
    repository: ((docker-organization))/stratos-postflight-job
- name: mariadb-helm-image
  type: docker-image
  source:
    username: ((docker-username))
    password: ((docker-password))
    repository: ((docker-organization))/stratos-mariadb
- name: ui-helm-image
  type: docker-image
  source:
    username: ((docker-username))
    password: ((docker-password))
    repository: ((docker-organization))/stratos-console

groups:
- name: tests
  jobs:
  - build-helm-images
  - build-aio-image

jobs:
- name: build-helm-images
  plan:
  - get: stratos
  - get: after-midnight
    trigger: true
  - aggregate:
    - do:
      - put: jetstream-helm-image
        params:
          dockerfile: stratos/deploy/Dockerfile.bk
          build: stratos/
          target_name:  prod-build
          tag_as_latest: true
      - put: postflight-helm-image
        params:
          dockerfile: stratos/deploy/Dockerfile.bk
          build: stratos/
          target_name:  postflight-job
          tag_as_latest: true
      - put: mariadb-helm-image
        params:
          dockerfile: stratos/deploy/db/Dockerfile.mariadb
          build: stratos/deploy/db
          tag_as_latest: true
      - put: ui-helm-image
        params:
          dockerfile: stratos/deploy/Dockerfile.ui
          build: stratos/
          target_name: prod-build
          tag_as_latest: true
      timeout: 2h30m

- name: build-aio-image
  public: true
  serial: true
  plan:
  - get: stratos
  - get: after-midnight
    trigger: true
  - put: aio-docker-image
    params:
      build: stratos
      dockerfile: stratos/deploy/Dockerfile.all-in-one
      tag_as_latest: false
