resources:
- name: stratos-ui
  type: git
  source:
    branch: {{stratos-ui-branch}}
    uri: git@github.com:SUSE/stratos-ui.git
    private_key: {{github-private-key}}
- name: helm-charts-repository
  type: git
  source:
    branch: master
    private_key: {{github-private-key}}
    uri: {{release-helm-repo}}
jobs:
- name: sync-sle-release
  plan:
  - get: stratos-ui
  - get: helm-charts-repository
  - do:
    - task: build
      privileged: true
      timeout: 30m
      file: stratos-ui/deploy/ci/tasks/release/sync-official-release.yml
      params:
        GITHUB_TOKEN: {{github-access-token}}
        GIT_USER: {{concourse-user}}
        GIT_EMAIL: {{concourse-email}}
        GIT_PRIVATE_KEY: {{github-private-key}}
        STAGING_REPOSITORY: {{staging-repository}}
        STAGING_REPOSITORY_USERNAME: {{staging-repository-username}}
        STAGING_REPOSITORY_PASSWORD: {{staging-repository-password}}
        STAGING_REPOSITORY_ORG: {{staging-repository-organization}}
        RELEASE_REPOSITORY: {{release-repository}}
        RELEASE_REPOSITORY_USERNAME: {{release-repository-username}}
        RELEASE_REPOSITORY_PASSWORD: {{release-repository-password}}
        RELEASE_REPOSITORY_ORG: {{release-repository-organization}}
        RELEASE_HELM_STABLE_FOLDER: {{release-helm-stable-folder}}
        RELEASE_SCRIPT: {{release-script}}
        MINIO_SERVER_ENDPOINT: {{minio-server-endpoint}}
        MINIO_ACCESS_KEY: {{minio-access-key}}
        MINIO_SECRET_KEY: {{minio-secret-access-key}}
