---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: ci-registry.capbristol.com:5000/opensuse
    insecure_registries: [ "ci-registry.capbristol.com:5000" ]

inputs:
- name: stratos
outputs:
- name: dev-certs-output
run:
  path: sh
  args:
  - -exc
  - |
    export CERTS_PATH=dev-certs-output/dev-certs
    ./stratos/deploy/tools/generate_cert.sh
